### ISSUE TITLE
Difficult to tell what changed from protractor-flake

### ISSUE THREAD

**Issue by chrismwendt** [ts-blink/protractor-junit-flake#1]
Since you wiped the history, it's difficult to find out what the difference between this and the original https://github.com/NickTomlin/protractor-flake is.

**Comment by ashubham** [comment]
@chrismwendt This project wasnt meant to be a fork of protractor-flake. The way the two project handle error parsing is very different. Though, I agree its inspired, and reuses some artifacts from protractor-flake.

**Comment by chrismwendt** [comment]
I understand that the plan was to not merge back any changes. However, since this code came from the other repo and got modified, it would be easier to determine what changed and why by looking at the diff than to read the code in its entirety. It wouldn't have even required more effort to preserve (or squash) the history. Alternatively, an informational message at the top of the README would help too.
